package export

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/Bharath-code/promptvault/internal/model"
)

type Format string

const (
	FormatSkillMD    Format = "skill.md"
	FormatAgentsMD   Format = "agents.md"
	FormatClaudeMD   Format = "claude.md"
	FormatCursorRules Format = "cursorrules"
	FormatWindsurf   Format = "windsurf"
	FormatMarkdown   Format = "markdown"
	FormatJSON       Format = "json"
	FormatPlainText  Format = "text"
)

// Exporter converts prompts to various formats
type Exporter struct {
	prompts []*model.Prompt
}

func New(prompts []*model.Prompt) *Exporter {
	return &Exporter{prompts: prompts}
}

// Export converts prompts to the specified format
func (e *Exporter) Export(format Format) (string, error) {
	switch format {
	case FormatSkillMD:
		return e.toSkillMD(), nil
	case FormatAgentsMD:
		return e.toAgentsMD(), nil
	case FormatClaudeMD:
		return e.toClaudeMD(), nil
	case FormatCursorRules:
		return e.toCursorRules(), nil
	case FormatWindsurf:
		return e.toWindsurf(), nil
	case FormatMarkdown:
		return e.toMarkdown(), nil
	case FormatJSON:
		return e.toJSON(), nil
	case FormatPlainText:
		return e.toPlainText(), nil
	default:
		return "", fmt.Errorf("unknown format: %s", format)
	}
}

// toSkillMD generates a Claude Code SKILL.md file
func (e *Exporter) toSkillMD() string {
	var b strings.Builder

	b.WriteString("# Prompt Skills\n\n")
	b.WriteString(fmt.Sprintf("*Generated by PromptVault on %s*\n\n", time.Now().Format("2006-01-02")))
	b.WriteString("## Overview\n\n")
	b.WriteString(fmt.Sprintf("This skill file contains %d curated prompts organized by tech stack.\n\n", len(e.prompts)))
	b.WriteString("## Usage\n\n")
	b.WriteString("Claude will load these prompts as contextual skills based on the current task.\n\n")
	b.WriteString("---\n\n")

	// Group by stack
	byStack := e.groupByStack()
	for stack, prompts := range byStack {
		b.WriteString(fmt.Sprintf("## %s\n\n", stackToTitle(stack)))
		for _, p := range prompts {
			b.WriteString(fmt.Sprintf("### %s\n\n", p.Title))
			if len(p.Models) > 0 {
				b.WriteString(fmt.Sprintf("*Optimized for: %s*\n\n", strings.Join(p.Models, ", ")))
			}
			b.WriteString("```\n")
			b.WriteString(p.Content)
			b.WriteString("\n```\n\n")
			if len(p.Tags) > 0 {
				b.WriteString(fmt.Sprintf("Tags: %s\n\n", strings.Join(p.Tags, ", ")))
			}
		}
	}

	return b.String()
}

// toAgentsMD generates an AGENTS.md file (OpenAI format)
func (e *Exporter) toAgentsMD() string {
	var b strings.Builder

	b.WriteString("# AGENTS.md\n\n")
	b.WriteString(fmt.Sprintf("Generated by PromptVault — %s\n\n", time.Now().Format("2006-01-02")))
	b.WriteString("## Agent Instructions\n\n")
	b.WriteString("The following prompts define agent behavior and coding standards for this project.\n\n")

	for _, p := range e.prompts {
		b.WriteString(fmt.Sprintf("### %s\n\n", p.Title))
		b.WriteString(p.Content)
		b.WriteString("\n\n")
		if p.Stack != "" {
			b.WriteString(fmt.Sprintf("*Stack: %s*\n\n", p.Stack))
		}
		b.WriteString("---\n\n")
	}

	return b.String()
}

// toClaudeMD generates a CLAUDE.md snippet
func (e *Exporter) toClaudeMD() string {
	var b strings.Builder

	b.WriteString("# CLAUDE.md\n\n")
	b.WriteString("<!-- Generated by PromptVault. Add this to your project's CLAUDE.md -->\n\n")
	b.WriteString("## Coding Standards and AI Prompts\n\n")

	for _, p := range e.prompts {
		b.WriteString(fmt.Sprintf("### %s\n\n", p.Title))
		b.WriteString(p.Content)
		b.WriteString("\n\n")
	}

	return b.String()
}

// toCursorRules generates a .cursorrules file
func (e *Exporter) toCursorRules() string {
	var b strings.Builder

	b.WriteString("# .cursorrules\n")
	b.WriteString("# Generated by PromptVault\n\n")

	for _, p := range e.prompts {
		b.WriteString(fmt.Sprintf("# %s\n", p.Title))
		b.WriteString(p.Content)
		b.WriteString("\n\n")
	}

	return b.String()
}

// toWindsurf generates a Windsurf rules file
func (e *Exporter) toWindsurf() string {
	var b strings.Builder

	b.WriteString("# Windsurf Rules\n")
	b.WriteString("# Generated by PromptVault\n\n")

	for _, p := range e.prompts {
		b.WriteString(fmt.Sprintf("## %s\n\n", p.Title))
		b.WriteString(p.Content)
		b.WriteString("\n\n")
	}

	return b.String()
}

// toMarkdown generates a readable Markdown doc
func (e *Exporter) toMarkdown() string {
	var b strings.Builder

	b.WriteString("# PromptVault Export\n\n")
	b.WriteString(fmt.Sprintf("*Exported %s — %d prompts*\n\n", time.Now().Format("Jan 2, 2006"), len(e.prompts)))
	b.WriteString("---\n\n")

	byStack := e.groupByStack()
	for stack, prompts := range byStack {
		b.WriteString(fmt.Sprintf("## %s\n\n", stackToTitle(stack)))
		for _, p := range prompts {
			b.WriteString(fmt.Sprintf("### %s\n\n", p.Title))
			b.WriteString(fmt.Sprintf("**Stack:** `%s`\n\n", p.Stack))
			if len(p.Models) > 0 {
				b.WriteString(fmt.Sprintf("**Models:** %s\n\n", strings.Join(p.Models, ", ")))
			}
			if len(p.Tags) > 0 {
				tags := make([]string, len(p.Tags))
				for i, t := range p.Tags {
					tags[i] = "`" + t + "`"
				}
				b.WriteString(fmt.Sprintf("**Tags:** %s\n\n", strings.Join(tags, " ")))
			}
			b.WriteString("**Prompt:**\n\n")
			b.WriteString("```\n")
			b.WriteString(p.Content)
			b.WriteString("\n```\n\n")
			b.WriteString(fmt.Sprintf("*Used %d times*\n\n", p.UsageCount))
			b.WriteString("---\n\n")
		}
	}

	return b.String()
}

// jsonPrompt is a JSON-safe representation
type jsonPrompt struct {
	ID         string   `json:"id"`
	Title      string   `json:"title"`
	Content    string   `json:"content"`
	Stack      string   `json:"stack"`
	Tags       []string `json:"tags"`
	Models     []string `json:"models"`
	Verified   bool     `json:"verified"`
	UsageCount int      `json:"usage_count"`
}

// toJSON generates proper JSON output using encoding/json
func (e *Exporter) toJSON() string {
	items := make([]jsonPrompt, len(e.prompts))
	for i, p := range e.prompts {
		tags := p.Tags
		if tags == nil {
			tags = []string{}
		}
		models := p.Models
		if models == nil {
			models = []string{}
		}
		items[i] = jsonPrompt{
			ID:         p.ID,
			Title:      p.Title,
			Content:    p.Content,
			Stack:      p.Stack,
			Tags:       tags,
			Models:     models,
			Verified:   p.Verified,
			UsageCount: p.UsageCount,
		}
	}

	data, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return "[]"
	}
	return string(data) + "\n"
}

// toPlainText generates plain text
func (e *Exporter) toPlainText() string {
	var b strings.Builder
	for i, p := range e.prompts {
		b.WriteString(fmt.Sprintf("=== %s ===\n\n", p.Title))
		b.WriteString(p.Content)
		b.WriteString("\n\n")
		if i < len(e.prompts)-1 {
			b.WriteString("---\n\n")
		}
	}
	return b.String()
}

// groupByStack groups prompts by their stack path
func (e *Exporter) groupByStack() map[string][]*model.Prompt {
	groups := make(map[string][]*model.Prompt)
	for _, p := range e.prompts {
		key := p.Stack
		if key == "" {
			key = "general"
		}
		groups[key] = append(groups[key], p)
	}
	return groups
}

// stackToTitle converts "frontend/react/hooks" to "Frontend > React > Hooks"
func stackToTitle(stack string) string {
	parts := strings.Split(stack, "/")
	titled := make([]string, len(parts))
	for i, p := range parts {
		if len(p) > 0 {
			titled[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(titled, " > ")
}
